-- MySQL Script generated by MySQL Workbench
-- Sat Jun 10 18:30:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especie` (
  `nombre` VARCHAR(45) NOT NULL,
  `orden` VARCHAR(45) NULL DEFAULT NULL,
  `familia` VARCHAR(45) NULL DEFAULT NULL,
  `genus` VARCHAR(45) NULL DEFAULT NULL,
  `nombre_comun` VARCHAR(45) NOT NULL,
  `invasivo` TINYINT NULL DEFAULT NULL,
  `conservacion` TINYINT NULL DEFAULT NULL,
  `taxon_ID` INT NULL DEFAULT NULL,
  `segundo_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `subgenus` VARCHAR(45) NULL DEFAULT NULL,
  `taxon_rank` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `nombre_especie_UNIQUE` ON `mydb`.`especie` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`avistamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avistamiento` (
  `avistamiento_id` VARCHAR(45) NOT NULL,
  `especie` VARCHAR(45) NOT NULL,
  `basis_of_record` VARCHAR(45) NULL DEFAULT NULL,
  `institution_code` VARCHAR(45) NOT NULL,
  `organism_quantity` INT NULL DEFAULT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `sex` VARCHAR(45) NULL DEFAULT NULL,
  `reproductive_condition` TINYINT NULL DEFAULT NULL,
  `behavior` VARCHAR(45) NULL DEFAULT NULL,
  `occurrence_status` VARCHAR(45) NULL DEFAULT NULL,
  `identified` TINYINT NULL DEFAULT NULL,
  `year` INT NOT NULL,
  `month` INT NOT NULL,
  `day` INT NOT NULL,
  `time` TIME NULL DEFAULT NULL,
  `contient` VARCHAR(45) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `state_province` VARCHAR(45) NOT NULL,
  `locality` VARCHAR(45) NULL DEFAULT NULL,
  `place` VARCHAR(45) NULL DEFAULT NULL,
  `coordinate_system` VARCHAR(45) NULL DEFAULT NULL,
  `clima` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`avistamiento_id`),
  CONSTRAINT `fk_avistamiento_especie`
    FOREIGN KEY (`especie`)
    REFERENCES `mydb`.`especie` (`nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `id_avistamiento_UNIQUE` ON `mydb`.`avistamiento` (`avistamiento_id` ASC) VISIBLE;

CREATE INDEX `fk_avistamiento_especie1_idx` ON `mydb`.`avistamiento` (`especie` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`clima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clima` (
  `tipo` VARCHAR(45) NOT NULL,
  `altitud` INT NOT NULL,
  `temperatura_primavera_min` INT NOT NULL,
  `temperatura_primavera_max` INT NOT NULL,
  `temperatura_verano_min` INT NOT NULL,
  `temperatura_verano_max` INT NOT NULL,
  `temperatura_otoño_min` INT NOT NULL,
  `temperatura_otoño_max` INT NOT NULL,
  `temperatura_invierno_min` INT NOT NULL,
  `temperatura_invierno_max` INT NOT NULL,
  `precipitacion_min` INT NOT NULL,
  `precipitacion_max` INT NOT NULL,
  PRIMARY KEY (`tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `tipo_UNIQUE` ON `mydb`.`clima` (`tipo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `day` INT NOT NULL,
  `month` INT NOT NULL,
  `year` INT NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`day`, `month`, `year`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`evento_natural`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento_natural` (
  `evento_day` INT NOT NULL,
  `evento_month` INT NOT NULL,
  `evento_year` INT NOT NULL,
  `temperatura` TINYINT NOT NULL,
  `viento` TINYINT NOT NULL,
  `lluvia` TINYINT NOT NULL,
  PRIMARY KEY (`evento_day`, `evento_month`, `evento_year`),
  CONSTRAINT `fk_evento_natural_evento1`
    FOREIGN KEY (`evento_day` , `evento_month` , `evento_year`)
    REFERENCES `mydb`.`evento` (`day` , `month` , `year`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `provincia` VARCHAR(45) NOT NULL,
  `codigo_pais` INT NULL DEFAULT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codigo_CCAA` VARCHAR(45) NULL DEFAULT NULL,
  `CCAA` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_provincia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `mydb`.`region` (`provincia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`region_tiene_clima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region_tiene_clima` (
  `region_nombre` VARCHAR(45) NOT NULL,
  `clima_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`region_nombre`, `clima_tipo`),
  CONSTRAINT `fk_region_has_clima_clima1`
    FOREIGN KEY (`clima_tipo`)
    REFERENCES `mydb`.`clima` (`tipo`),
  CONSTRAINT `fk_region_has_clima_region1`
    FOREIGN KEY (`region_nombre`)
    REFERENCES `mydb`.`region` (`provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_region_has_clima_clima1_idx` ON `mydb`.`region_tiene_clima` (`clima_tipo` ASC) VISIBLE;

CREATE INDEX `fk_region_has_clima_region1_idx` ON `mydb`.`region_tiene_clima` (`region_nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`vive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vive` (
  `region_id` VARCHAR(45) NOT NULL,
  `especie_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`region_id`, `especie_nombre`),
  CONSTRAINT `fk_vive_especie1`
    FOREIGN KEY (`especie_nombre`)
    REFERENCES `mydb`.`especie` (`nombre`),
  CONSTRAINT `fk_vive_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `mydb`.`region` (`provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_vive_region1_idx` ON `mydb`.`vive` (`region_id` ASC) VISIBLE;

CREATE INDEX `fk_vive_especie1_idx` ON `mydb`.`vive` (`especie_nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`evento_en_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento_en_region` (
  `evento_day` INT NOT NULL,
  `evento_month` INT NOT NULL,
  `evento_year` INT NOT NULL,
  `region_provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`evento_day`, `evento_month`, `evento_year`, `region_provincia`),
  CONSTRAINT `fk_evento_has_region_evento1`
    FOREIGN KEY (`evento_day` , `evento_month` , `evento_year`)
    REFERENCES `mydb`.`evento` (`day` , `month` , `year`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_has_region_region1`
    FOREIGN KEY (`region_provincia`)
    REFERENCES `mydb`.`region` (`provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_evento_has_region_region1_idx` ON `mydb`.`evento_en_region` (`region_provincia` ASC) VISIBLE;

CREATE INDEX `fk_evento_has_region_evento1_idx` ON `mydb`.`evento_en_region` (`evento_day` ASC, `evento_month` ASC, `evento_year` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
